### PR TITLE
don't self-close tags in the template

### PR DESCRIPTION
**Pull request by benib**
This replaces the self-closing `<div />` with `<div></div>` as self-closing the tags leads to problems with the elements not being in the dom and the directive js code throwing errors because elements don't exists.

### CODE REVIEW

**Comment by przno** [comment]
Hi Beni. I made you a collaborator, so you should be able to merge/commit now. Thank you for help.

And to this error - yes a trivial error from my side...

**Comment by benib** [comment]
@przno cool. Are you fine with using the GitHub release feature to tag releases? Then I'd tag 0.1.5 with this fix merged into master...

**Comment by przno** [comment]
@benib  Didn't even know there is such a feature, I'm bit a newbie to GitHub. So please, feel free to proceed.

**Comment by benib** [comment]
This is released as 0.1.5

**Pull request merged**
